name:                convert-labels
version:             0.1.0.0
github:              "githubuser/convert-labels"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/convert-labels#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.2.0
- directory >= 1.2.2.2
- hip >= 1.3.0.0

library:
  source-dirs: src

executables:
  convert-labels-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convert-labels

tests:
  convert-labels-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convert-labels
